### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by dsibenik** [floriandejonckheere/powerampd#1]
Hey, great idea, exactly what I need. Does it still work? Could you post detailed instructions on how to set up?

**Comment by floriandejonckheere** [comment]
Hi! Unfortunately I haven't used the project since I have abandoned it some years ago. It should still work, but the code is not up to date with either the Android libraries or the MPD protocol. You can see what MPD commands are already implemented in [IMPLEMENTATION.md](https://github.com/floriandejonckheere/powerampd/blob/master/IMPLEMENTATION.md) if you'd like to continue to use the code.
